# -*- coding: utf-8 -*-
"""lab10

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13P1_KZSjiyp85MnN2hR9Eiv9yAf_Ynbh
"""

from flask import Flask, request
from flask_cors import CORS
app = Flask(__name__)
CORS(app)
keys = []
values = []

# api名稱 : /
@app.route('/',methods=['GET'])
def root():
  return 'ok' 

# api名稱 : /set
@app.route('/set',methods=['POST'])
def set():
  a = 0
  data = request.form.to_dict()
  print(data)
  for i in keys :  
    if i == data['key'] : # 如果data的key已經存在
      a = 1
      return 'key exists'  
  if a == 0 :        # 如果data的key原本不存在
    keys.append(data['key'])  # 新增值
    values.append(data['value'])
    return 'set success' 

# api名稱 : /key_list
@app.route('/key_list',methods=['GET'])
def key_list():
    return str(keys) # 回傳整個 key list

# api名稱 : /get_value/{key}
@app.route('/get_value/<key_a>',methods=['GET'])
def getvalue(key_a):
  a = 0
  for i in keys :  
     if i == key_a : # 如果data的key已經存在
        res_value = values[keys.index(key_a)]
        a == 1
        return res_value  # 回傳value值
  if a == 0 :      # 如果data的key原本不存在
     return 'key not found'

# api名稱 : /update_value
@app.route('/update_value',methods=['POST'])
def update():
  a = 0
  data_u = request.form.to_dict()
  print(data_u)
  for i in keys :  
    if i == data_u['key'] :  # 如果 data_u 的 key 在存在於key list裡面
      values[keys.index(i)] = data_u['value']
      a = 1
      return 'update success' 
  if a == 0:           # 如果 data_u 的 key 不存在於key list裡面
      return 'key does not exist' 

# api名稱 : /delete/{key}
@app.route('/delete/<key_d>',methods=['GET'])
def delete(key_d):
  a = 0
  for i in keys :
    if i == key_d :  # 如果傳進來的 key_d 存在於 key list 裡面
      delete_index = keys.index(i)
      keys.remove(i)
      values.pop(delete_index)
      a = 1
      return 'delete success' 
  if a == 1:       # 如果傳進來的 key_d 不存在於 key list 裡面
      return 'key not found' 

app.run(host="0.0.0.0", port=3000, debug=True)