# -*- coding: utf-8 -*-
"""lab07.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_vbMEqI14hNO8wtTXxrMMpaMWRXSaWxy
"""

class Animal():
    def __init__(self, weight, mood):
        self.weight = weight
        self.mood = mood
    def feed(self):
        pass
    def walk(self):
        pass
    def bath(self):
        pass
    
class Dogs(Animal):
    def __init__(self, weight, mood):
        super().__init__(weight,mood)   #沿用父類別的屬性
    def feed(self,time):           #計算餵食對體重及心情的改變
        self.weight += time*0.2
        self.mood += time*1
        return self.weight, self.mood
    def walk(self,time):           #計算散步對體重及心情的改變
        self.weight -= time*0.2
        self.mood += time*2
        return self.weight, self.mood
    def bath(self,time):           #計算洗澡對體重及心情的改變
        self.weight += 0
        self.mood -= time*2
        return self.weight, self.mood
    def printf(self, n_feed, n_walk, n_bath):
        Dogs.feed(self,n_feed)       #呼叫前面所定的方法
        Dogs.walk(self,n_walk)
        Dogs.bath(self,n_bath)
        print("狗狗現在的體重=",self.weight,"kg, 心情",self.mood)

class Cats(Animal):
    def __init__(self, weight, mood):
        super().__init__(weight,mood)   #沿用父類別的屬性
    def feed(self,time):           #計算餵食對體重及心情的改變
        self.weight += time * 0.1
        self.mood += time * 1
        return self.weight, self.mood
    def walk(self,time):           #計算散步對體重及心情的改變
        self.weight -= time * 0.1
        self.mood -= time * 1
        return self.weight, self.mood
    def bath(self,time):           #計算洗澡對體重及心情的改變
        self.weight += 0
        self.mood -= time * 2
        return self.weight, self.mood
    def printf(self, n_feed, n_walk, n_bath):
        Cats.feed(self,n_feed)       #呼叫前面所定的方法
        Cats.walk(self,n_walk)
        Cats.bath(self,n_bath)
        print("貓貓現在的體重=",self.weight,"kg, 心情",self.mood)

dog = Dogs(4.8, 65) 
dog.printf(18, 10, 4) 

cat = Cats(8.2, 60) 
cat.printf(40, 7, 1)