# -*- coding: utf-8 -*-
"""lab09_client

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wIUdrtSiisVhb9GmqzLIfVQFG05Sr11_
"""

# -*- coding: utf-8 -*-
import socket

HOST = '10.3.141.1'
PORT = 8000

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect((HOST, PORT))
print('Connected to: %s:%s' % (HOST, PORT))

while True:
    outdata = input('send: ')
    s.send(outdata.encode())
    if outdata == 'EXIT': # connection closed
        s.close()
        print('Closed connection.')
        break
    indata = s.recv(1024)
    print(indata.decode())