# -*- coding: utf-8 -*-
"""lab09_server_plus

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-CSioDJqWYYcLld1QYxqCuvMW-fZ8P9V
"""

import socket
from threading import Thread


HOST = '10.3.141.1'
PORT = 8000
threads = []

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
s.bind((HOST, PORT))
s.listen(5)

print('Server start at: %s:%s' % (HOST, PORT))

def sever():
  while True:
      print('Wait for connection...')
      conn, addr = s.accept()
      print('Connected by ' + str(addr))

      while True:
          indata = conn.recv(1024)
          if indata.decode() == 'EXIT': # connection closed
              conn.close()
              print(str(addr) + 'closed connection.')
              break
          print(str(addr) + ':' + indata.decode())
          outdata = 'Echo: ' + indata.decode()
          conn.send(outdata.encode())

while True:
  t = Thread(target=server)
  t.start()
  threads.append(t)