# -*- coding: utf-8 -*-
"""lab06.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yw3sGyi9t8HmFej-gtmssqLakdwKmAv6
"""

def gcd(a,b):
  i=0
  num1 = max(a,b)
  num2 = min(a,b)
  while num2 != 0: #進行輾轉相除法
    i=1
    r = num1 % num2
    num1 = num2
    num2 = r
  if num2 == 0 and i != 1: #判斷num2是否為一開始就等於0
    return num2
  elif num2 == 0 : #判斷num2是否為最大公因數
    return num1
  else:
    return gcd(num1,num2) 

ans1 = gcd(80, 20)
ans2 = gcd(10, 0)
ans3 = gcd(19, 20)
if ans1 == 0:
  print("0沒有gcd")
elif ans1 == 1:
  print("80和20互質")
else:
  print("80和20的gcd=",ans1)
if ans2 == 0:
  print("0沒有gcd")
elif ans2 == 1:
  print("10和0互質")
else:
  print("10和0的gcd=",ans2)
if ans3 == 0:
  print("0沒有gcd")
elif ans3 == 1:
  print("19和20互質")
else:
  print("19和20的gcd=",ans3)